name: home_management_app
description: A new Flutter project.
version: 1.0.10+11

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  http: ^1.1.0
  fl_chart: ^0.45.1
  encrypt: ^5.0.1
  shared_preferences: ^2.0.13
  get_it: ^7.2.0
  injectable: ^2.3.0
  intl: ^0.18.1
  datetime_picker_formfield: ^2.0.0
  flutter_speed_dial: ^7.0.0
  flip_card: ^0.7.0
  local_auth: ^2.1.6
  package_info: ^2.0.2
  skeletons: ^0.0.3
  flutter_slidable: ^3.0.0
  grouped_list: ^5.0.1
  logger: ^2.0.2
  uuid: ^4.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.6.2

flutter:
  uses-material-design: true
