name: home_management_app
description: A new Flutter project.
version: 1.0.10+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  http: ^0.13.4
  fl_chart: ^0.41.0
  encrypt: ^5.0.1
  shared_preferences: ^2.0.13
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  datetime_picker_formfield: ^2.0.0
  flutter_speed_dial: ^3.0.5
  flip_card: ^0.6.0
  local_auth: ^1.1.10
  package_info: ^2.0.2
  skeletons: ^0.0.3
  flutter_slidable: ^1.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
